service: caixaflow
image: gustavodamassa/caixaflow

servers:
  web:
    - 192.168.0.244

# Proxy sem SSL — Cloudflare Tunnel termina o TLS externamente
proxy:
  ssl: false
  host: caixaflow.gustavohdev.com.br
  app_port: 80
  forward_headers: true

registry:
  username: gustavodamassa
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - DB_PASSWORD
    - SECRET_KEY_BASE
  clear:
    DB_HOST: caixaflow-db
    DB_PORT: "5432"
    DB_USERNAME: caixaflow
    REDIS_URL: redis://caixaflow-redis:6379/0
    RAILS_LOG_LEVEL: info
    RAILS_ENV: production

builder:
  arch: amd64

ssh:
  user: gustavo

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell:   app exec --interactive --reuse "bash"
  logs:    app logs -f
  dbc:     app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "caixaflow_storage:/rails/storage"

asset_path: /rails/public/assets

accessories:
  db:
    image: postgres:16-alpine
    host: 192.168.0.244
    port: "127.0.0.1:5434:5432"
    env:
      secret:
        - POSTGRES_PASSWORD
      clear:
        POSTGRES_USER: caixaflow
        POSTGRES_DB: caixaflow_production
    directories:
      - data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    host: 192.168.0.244
    port: "127.0.0.1:6381:6379"
    directories:
      - data:/data
